version: '3'
services:
  neo4j:
    image: neo4j:5.7-enterprise
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
    environment: 
      # Raise memory limits
      NEO4J_AUTH: neo4j/AegiScan
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms.memory.heap.initial_size: 1G
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_whitelist: apoc.*
      NEO4J_dbms_security_procedures_unrestricted: apoc.*